
# setup -------------------------------------------------------------------

library(tidyverse)
library(vegan)  
library(glue)


eea <- read_csv("data/combined_2019_activity_calcs_20220325.csv") %>% 
  mutate(across(where(is.numeric), ~ifelse(.<0, 0, .))) %>%   # set small neg activities to 0, need to fix this in the QC script
  filter(sample_id != "172")   # drop outlier 

# grabbing site & soil metadata from the PLFA file 
meta <- read_csv("data/cig_plfa_abs_abundance_mgmt_meta_20220421.csv") %>%
  select(
    sample_id,
    region,
    site,
    treatment,
    position,
    pH,
    som_loi,
    sand_perc,
    clay_perc,
    silt_perc,
    hydro_texcl,
    total_dist,
    avg_dist,
    nseasons_cover,
    prop_cover,
    cover_group,
    nspec_total,
    nspec_avg_yr,
    n_unique_spec_5yr
  )

eea.meta <- inner_join(eea, meta, by = "sample_id")

# drop SAA (side project)
eea.meta <- filter(eea.meta, !site=="SAA")
# keep only farm treatments 
eea.meta <-  filter(eea.meta, treatment =="CV"|treatment=="SH")
# drop rows with missing values for any EEAs
eea.meta <- eea.meta[complete.cases(eea.meta),]

eea.meta <- eea.meta %>% 
  mutate(region = case_when(
    region == "MW" ~ "SE",
    region == "SW" ~ "SW", 
    region == "ST" ~ "C", 
    region == "RR" ~ "NW"
  ), 
  position = ifelse(eea.meta$position == "A", "Upper", "Lower"))


eea.meta$site <-  as.factor(eea.meta$site)
eea.meta$treatment <-  as.factor(eea.meta$treatment)
eea.meta$region <-  as.factor(eea.meta$region)
eea.meta$position <-  as.factor(eea.meta$position)
eea.meta$hydro_texcl <-  as.factor(eea.meta$hydro_texcl)


#create the ordination 

#need only the activity columns for the distance matrix
activ <-  eea.meta%>%
  select(contains('activity'))

#continuous mgmt/environmental columns for vector fitting
env.eea <-  eea.meta[c(
  "pH",
  "som_loi",
  "sand_perc",
  "clay_perc",
  "silt_perc",
  "total_dist",
  "nspec_avg_yr",
  "prop_cover"
)]


# ordination --------------------------------------------------------------

# can compare different ways to do the ranking
rankindex(scale(env.eea), activ, c("gower", "euc", "man", "bray", "jac", "kul", "binomial", "altGower"), method="spearman")
#I'm not really using this info, went with Bray as most common choice


# set seed for reproducibility 
# sfgrmin = scale factor gradient minimum
set.seed(20220426)
ord_activ = metaMDS(activ,
                    distance="bray", # dissimilarity index used in vegdist()
                    # maxit = 100,
                    k= 2, # n dimensions
                    sfgrmin = 1e-9, # convergence criteria passed to monoMDS, default is 1e-7
                    trymax = 300, # max n random starts in search of stable condition
                    autotransform =FALSE,
                    noshare = .1, # threshold proportion of site pairs w/ no shared species, triggers stepacross
                    trace = 1, # default, controls progress printout
                    plot = FALSE,
                    zerodist = "add") # handling of zero dissimilarities, "add" a small positive value

ord_activ

ord_stress <- ord_activ[["stress"]]

#Using the scores function from vegan to extract the 
#"site", i.e row, scores and convert to a data.frame
#join with other data for plotting
data.scores.l <-  as.data.frame(scores(ord_activ))  
data.scores.l <-  cbind(data.scores.l, eea.meta)


#"species" scores are for plotting individual enzyme activities, 
#probably not useful in this case
species.scores.l <-  as.data.frame(scores(ord_activ, "species"))
species.scores.l$species <-  row.names(species.scores.l)

species.scores.l <- species.scores.l %>% 
  mutate(species = case_when(
    species == "BG_activity" ~ "BG",
    species == "Cello_activity" ~ "CBH", 
    species == "NAG_activity" ~ "NAG", 
    species ==  "P_activity" ~ "PASE"
  ))


# environmental fit -------------------------------------------------------

#fit your environmental continuous variables to NMDS space

fit.l = envfit(ord_activ, env.eea[c("pH", "som_loi", "clay_perc")], perm = 1000,
               na.rm = TRUE)

fit.l
# som, pH, clay significant

#for plotting
fit.scoresl <- as.data.frame(scores(fit.l, display = "vectors"))
fit.scoresl$covars = as.factor(rownames(fit.scoresl))
fit.scoresl$covars = c("pH" = "pH", "som_loi" = "SOM", "clay_perc" = "Clay") 


# PERMANOVA ---------------------------------------------------------------

#permanova
#permanova uses the same distance matrix generated by
#nmds and checks whether the groups you proposed are different
#within that matrix
eea.dist <-  vegdist(activ, method="bray", na.rm=T) 

#  PERMANOVA w/ structure (site = blocks) defined
# in the permutations arg, see adonis docs

# define permutation design
# blocking by site
cig.perm <- permute::how(blocks = eea.meta$site, 
                         nperm = 1000)

set.seed(12) # set seed for reproducible result
eea.perm.strat = adonis(eea.dist~treatment*position*region,
                        permutations = cig.perm,
                        data = eea.meta)

eea.perm.strat


# Plot 1 region w/ annotations --------------------------------------------

region_plot <- ggplot(data.scores.l,
       aes(x = NMDS1,
           y = NMDS2)) +
  stat_ellipse(aes(color = region), lwd = 1) +
  # xlim(-0.5, 0.4) +
  # ylim(-0.3, 0.5) +
  geom_point(aes(color = region,
                 shape = treatment), size = 2) +
  geom_segment(
    data = fit.scoresl,
    aes(
      x = 0,
      xend = NMDS1,
      y = 0,
      yend = NMDS2
    ),
    arrow = arrow(length = unit(0.25, "cm")),
    
    colour = "black",
    lwd = 1
  ) +
  geom_text(data = fit.scoresl,
            aes(x = NMDS1, y = NMDS2 + 0.05, label = covars),
            size =6) + 
  geom_text(data = species.scores.l, aes(x = NMDS1, y = NMDS2, label = species), 
            size = 6, fontface = "bold") +
  annotate(geom = "text", x = .86, y = 0.70, label = "PERMANOVA", size = 6) +
  annotate(geom = "text", x = 0.9, y = 0.60, label = "Region  p = 0.049", size = 6) +
  annotate(geom = "text", x = 0.8, y = 0.50, label = "R ^ 2  == 0.37", size = 6, parse = TRUE) +
  annotate(geom = "text", x = 1.0, y = -0.5, label = "Stress = 0.058", size = 6) +
  coord_equal() +
  theme_light() +
  theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 20, ),
        legend.text = element_text(size = 22),
        legend.title = element_text(size = 22)) +
  scale_shape_discrete(name = "management") +
  scale_color_brewer(type = "qual", palette = 6)

region_plot 

ggsave("eea_NMDS_region.png", region_plot, height = 5, width = 11, units = "in")


# Plot 2 hillslope with annotations ---------------------------------------

hill_plot <- ggplot(data.scores.l,
       aes(x = NMDS1,
           y = NMDS2)) +
  stat_ellipse(aes(color = position), lwd = 1) +
  geom_point(aes(color = position, shape = treatment)) +
  geom_text(data = species.scores.l, aes(x = NMDS1, y = NMDS2, label = species), 
            size = 4, fontface = "bold") +
coord_equal() + 
  theme_light() +
  theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 20, ),
        legend.text = element_text(size = 22),
        legend.title = element_text(size = 22), 
        strip.text = element_text(size = 20)) + 
  scale_color_brewer(type = "qual", palette = 2) +
  labs(caption = "EEA NMDS") + 
  scale_shape_discrete(name = "management") +
  facet_wrap(vars(region), nrow = 2) 

hill_plot

ggsave("eea_NMDS_position_facet.png", hill_plot, height = 5, width = 11, units = "in") 



# Old figure - now combined w/ PLFA biomass see  ----------------
# 02_plfa_nmds_farms_only.R univariate summaries 


eea.ud <- inner_join(eea, meta, by = "sample_id")

eea.long <- eea.meta %>%
  select(
    sample_id,
    BG_activity,
    Cello_activity,
    NAG_activity,
    P_activity,
    region,
    site,
    treatment,
    position
  )%>%
  pivot_longer(cols = contains("activity"), values_to = "activity", names_to = "enzyme") %>% 
  mutate(enzyme = case_when(
    enzyme == "BG_activity" ~ "BG",
    enzyme == "NAG_activity" ~ "NAG", 
    enzyme == "P_activity" ~ "PASE",
    enzyme == "Cello_activity" ~ "CBH"
  ))

activity_plot <- ggplot(data = eea.long, aes(x = treatment, y = activity, color = treatment)) + 
  geom_boxplot(show.legend = FALSE) + 
  geom_point(alpha = 0.5, position = position_dodge(width = 0.75), 
             show.legend = FALSE) +
  facet_grid(vars(enzyme), vars(region), scales = "free_y") +
  scale_color_manual(values = c("#440154FF", "#2A788EFF")) +
  scale_y_log10() +
  theme_light() + 
  theme(axis.text = element_text(size = 16),
        axis.title = element_text(size = 20, ),
        legend.text = element_text(size = 22),
        legend.title = element_text(size = 22), 
        strip.text = element_text(size = 20), 
        plot.title = element_text(size = 20)) + 
  xlab("Management Group") + 
  ylab(expression(nmol~h^-1~g^-1~dry~soil)) +
  ggtitle("Extracellular enzyme activities")

activity_plot

ggsave("eea_activity_grid_plot.png", activity_plot, width = 11.8, height = 6, units = "in")
  
  

